train:
    dreambooth:
        _target_: src.datasets.dreambooth.DreamBoothTrainDataset
        data_path: /Users/l0ver1ck/repos/genai-projects-2025/domashniy
        placeholder_token: sks
        class_name: man
        instance_transforms: ${transforms.instance_transforms.train}

val:
    dreambooth:
      _target_: src.datasets.dreambooth.DreamBoothLivingSmall
      data_path: /Users/l0ver1ck/repos/genai-projects-2025/domashniy
      placeholder_token: sks
      class_name: dog
